### ISSUE TITLE
Dataset size computations do not match Blackfynn platform

### ISSUE THREAD

**Issue by rlmv** [bvhpatel/SODA#132]
**Describe the issue**

The Blackfynn platform uses SI units (1MB = 1000 bytes) to display the size of packages and datasets, but the SODA uploader uses IEC units (1MiB = 1024 bytes). See: https://github.com/bvhpatel/SODA/blob/d20c48c05513a9f37495a39fd8d837c6d979e866/src/renderer.js#L2221-L2230

When datasets contain GBs of data this causes fairly large differences in dataset size between SODA and the Blackfynn app.

We have received bug reports from users who are confused about why the amount of data they uploaded using SODA does not match the amount of data in the Blackfynn platform. The total number of bytes is the same, but it is just a display problem.

**To Reproduce**

Steps that lead to the issue:
1. Upload files into an empty dataset
2. Make note of the total size of uploaded data displayed by SODA
3. Navigate to the Blackfynn app
4. Compare the size of the dataset in the platform.

**Expected behavior**

The size of the dataset in the SODA app matches the size of the dataset in the plaform.

**Operating system used:**
 - macOS 10.13.6

**Comment by bvhpatel** [comment]
@rlmv Thanks for pointing this out. This has been addressed (and tested). This would be visible to the users in our next release (planned for next week),

**Comment by rlmv** [comment]
Thanks @bvhpatel, I appreciate it!
