### ISSUE TITLE
filenames in manifests do not include the file extension

### ISSUE THREAD

**Issue by tgbugs** [bvhpatel/SODA#193]
In manifests filenames must be the full name of the file including the file extension. We enforce uniqueness on filenames and thus name.ext1 and name.ext2 would collide, we also cannot rely on the file type column to match the actual extension on the file.

**Comment by megasanjay** [comment]
Hi @tgbugs That's an important feature. To get to the bottom of this would you mind stating which version of the app you are on?

**Comment by tgbugs** [comment]
@megasanjay I'm seeing this from the other end in the SPARC curation pipelines, so not entirely sure. That does suggest that it might be good to somehow embed the SODA version into one of the metadata files. @bandrow @aankap2 any idea here?

**Comment by megasanjay** [comment]
That's a great idea for verifying manifest file integrity @bvhpatel. We'll add it to the top of the bug fix list at the current moment. If you are able to find out which SODA version that the users were on just drop an update on here. Thanks again.

**Comment by megasanjay** [comment]
@tgbugs We just tried to replicate the issue on our end with the latest release version of SODA. The app seems to work okay with our test cases. If you see any more datasets that seem to have the same issue we'll go through the app to determine if we missed something again. Thank you for reporting the issue.

**Comment by megasanjay** [comment]
This issue will be closed but please let us know how we can continue the discussion on including the SODA version in the metadata files.
