### ISSUE TITLE
Trouble logging into Pennsieve

### ISSUE THREAD

**Issue by stebbima** [bvhpatel/SODA#242]
I'm having trouble logging into Pennsieve from SODA. Neither the email address plus password nor the API key option will work, although they report slightly different errors. The error for the password option is most verbose so I've posted a screenshot here with developer view turned on. 

I'm able to log connect to Pennsieve using the pennsieve API as evidenced by the command line prompt. I would have thought this should be recognised by SODA when it starts but no. I generated a different API key for each application (the API and SODA) just in case, but it still doesn't work for some reason.

I'm using SODA version 4.5.1 under windows 10.

![SODAerror](https://user-images.githubusercontent.com/51691277/123929443-2a3e0800-d9d2-11eb-93d3-851556c73d96.jpg)

**Comment by megasanjay** [comment]
Hi @stebbima. SODA should automatically log into Pennsive via pre-existing API keys, that are present on your system, as long as it accesses the SPARC Organization. If you can connect to Pennsieve via the command line, SODA will read that key for the connection as well. Before we get into more in-depth debugging, could you try restarting SODA and/or your computer? You shouldn't have to enter any information when you start SODA.

**Comment by stebbima** [comment]
Dear Sanjay. I did try that. Still the same error. I also installed DODA on my computer at home and managed to log in with my password but it still requires the email and password every time I start SODA.

I mainly do SPARC work at work because of the large datasets I'm uploading. It would be very useful to get SODA working there.

Thanks

Martin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Sanjay Soundarajan ***@***.***>
Sent: Thursday, July 1, 2021 2:27:25 AM
To: bvhpatel/SODA ***@***.***>
Cc: Martin Stebbing ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [bvhpatel/SODA] Trouble logging into Pennsieve (#242)


External email: Please exercise caution

________________________________
Hi @stebbima<https://github.com/stebbima>. SODA should automatically log into Pennsive via pre-existing API keys, that are present on your system, as long as it accesses the SPARC Organization. If you can connect to Pennsieve via the command line, SODA will read that key for the connection as well. Before we get into more in-depth debugging, could you try restarting SODA and/or your computer? You shouldn't have to enter any information when you start SODA.

**Comment by bvhpatel** [comment]
Hi Martin! I am emailing you to try to schedule a zoom call so we can observe the issue live and perhaps understand it better (we have not been able to replicate the issue on our end).

**Comment by stebbima** [comment]
Dear Bavesh,

The time difference will make that interesting. Where exactly are you. If you are EDT then 4pm your time is 6 am my time which would work for me, but later would be better.

Cheers,

Martin

________________________________
From: Bhavesh Patel ***@***.***>
Sent: 01 July 2021 09:05
To: bvhpatel/SODA ***@***.***>
Cc: Martin Stebbing ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [bvhpatel/SODA] Trouble logging into Pennsieve (#242)


External email: Please exercise caution

________________________________
Hi Martin! I am emailing you to try to schedule a zoom call so we can observe the issue live and perhaps understand it better (we have not been able to replicate the issue on our end).
